# Project 4: Prediction of Agriculture Crop Production in India

## Machine Learning Internship

### Author
Fardeen Akmal

### Objective
To analyze agricultural data and build a machine learning model that predicts crop production using historical agricultural datasets.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Display all columns
pd.set_option("display.max_columns", None)

# Display all rows if needed
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
df1 = pd.read_csv("../data/raw/datafile.csv")
df2 = pd.read_csv("../data/raw/datafile (1).csv")
df3 = pd.read_csv("../data/raw/datafile (2).csv")
df4 = pd.read_csv("../data/raw/datafile (3).csv")
df5 = pd.read_csv("../data/raw/produce.csv")

print("All datasets loaded successfully!")

All datasets loaded successfully!

In [3]:
# Check the dimensions of all datasets

print("Dataset 1:", df1.shape)
print("Dataset 2:", df2.shape)
print("Dataset 3:", df3.shape)
print("Dataset 4:", df4.shape)
print("Dataset 5:", df5.shape)

Dataset 1: (13, 9)
Dataset 2: (49, 6)
Dataset 3: (55, 16)
Dataset 4: (78, 5)
Dataset 5: (429, 25)

In [4]:
# Display column names of each dataset

datasets = {
    "Dataset 1": df1,
    "Dataset 2": df2,
    "Dataset 3": df3,
    "Dataset 4": df4,
    "Dataset 5": df5
}

for name, df in datasets.items():
    print(f"\n{name}")
    print("-" * 50)
    print(df.columns.tolist())

Dataset 1
--------------------------------------------------
['Crop', '2004-05', '2005-06', '2006-07', '2007-08', '2008-09', '2009-10', '2010-11', '2011-12']

Dataset 2
--------------------------------------------------
['Crop', 'State', 'Cost of Cultivation (`/Hectare) A2+FL', 'Cost of Cultivation (`/Hectare) C2', 'Cost of Production (`/Quintal) C2', 'Yield (Quintal/ Hectare) ']

Dataset 3
--------------------------------------------------
['Crop             ', 'Production 2006-07', 'Production 2007-08', 'Production 2008-09', 'Production 2009-10', 'Production 2010-11', 'Area 2006-07', 'Area 2007-08', 'Area 2008-09', 'Area 2009-10', 'Area 2010-11', 'Yield 2006-07', 'Yield 2007-08', 'Yield 2008-09', 'Yield 2009-10', 'Yield 2010-11']

Dataset 4
--------------------------------------------------
['Crop', 'Variety', 'Season/ duration in days', 'Recommended Zone', 'Unnamed: 4']

Dataset 5
--------------------------------------------------
['Particulars', 'Frequency', 'Unit', ' 3-1993', ' 3-1994', ' 3-1995', ' 3-1996', ' 3-1997', ' 3-1998', ' 3-1999', ' 3-2000', ' 3-2001', ' 3-2002', ' 3-2003', ' 3-2004', ' 3-2005', ' 3-2006', ' 3-2007', ' 3-2008', ' 3-2009', ' 3-2010', ' 3-2011', ' 3-2012', ' 3-2013', ' 3-2014']

In [5]:
# Display the first 5 rows of each dataset

for name, df in datasets.items():
    print(f"\n{name}")
    display(df.head())

Dataset 1

,Crop,2004-05,2005-06,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12
0,Rice,100.0,101.0,99.0,105.0,112.0,121.0,117.0,110.0
1,Wheat,100.0,101.0,112.0,115.0,117.0,127.0,120.0,108.0
2,Coarse Cereals,100.0,107.0,110.0,115.0,113.0,123.0,122.0,136.0
3,Pulses,100.0,108.0,134.0,124.0,124.0,146.0,137.0,129.0
4,Vegetables,100.0,109.0,103.0,118.0,113.0,124.0,128.0,115.0

Dataset 2

,Crop,State,Cost of Cultivation (`/Hectare) A2+FL,Cost of Cultivation (`/Hectare) C2,Cost of Production (`/Quintal) C2,Yield (Quintal/ Hectare)
0,ARHAR,Uttar Pradesh,9794.05,23076.74,1941.55,9.83
1,ARHAR,Karnataka,10593.15,16528.68,2172.46,7.47
2,ARHAR,Gujarat,13468.82,19551.90,1898.30,9.59
3,ARHAR,Andhra Pradesh,17051.66,24171.65,3670.54,6.42
4,ARHAR,Maharashtra,17130.55,25270.26,2775.80,8.72

Dataset 3

,Crop,Production 2006-07,Production 2007-08,Production 2008-09,Production 2009-10,Production 2010-11,Area 2006-07,Area 2007-08,Area 2008-09,Area 2009-10,Area 2010-11,Yield 2006-07,Yield 2007-08,Yield 2008-09,Yield 2009-10,Yield 2010-11
0,Total Foodgrains,158.8,168.6,171.3,159.4,178.9,128.5,128.8,127.6,126.0,131.7,123.6,130.9,134.3,126.5,135.9
1,Rice,200.8,207.9,213.3,191.6,206.4,168.5,168.9,175.1,161.2,164.8,119.2,123.1,121.8,118.9,125.2
2,Wheat,131.6,136.4,140.1,140.3,150.8,115.0,115.2,114.0,116.9,119.5,114.4,118.4,122.8,120.0,126.3
3,Jowar,124.3,137.8,126.0,116.5,121.8,120.7,110.6,107.3,111.0,105.2,103.0,124.6,117.4,105.0,115.8
4,Bajra,136.4,161.5,143.9,105.4,167.9,94.5,95.1,87.0,88.5,95.6,144.3,169.7,165.4,119.0,175.8

Dataset 4

,Crop,Variety,Season/ duration in days,Recommended Zone,Unnamed: 4
0,Paddy,Chinsurah Rice (IET 19140),Medium,"Andhra Pradesh, Tamil Nadu, Gujarat, Orissa, a...",NaN
1,Paddy,(CNI 383-5-11),NaN,NaN,NaN
2,Paddy,IGKVR-1 (IET 19569),Mid-early,"Chhattisgarh, Madhya Pradesh and Orissa under ...",NaN
3,Paddy,IGKVR-2 (IET 19795),Medium,"Chhattisgarh, Bihar and Orissa under both irr...",NaN
4,Paddy,CR Dhan 401 (REETA),145-150,"Orissa, West Bengal, Tamil Nadu and Andhra Pra...",NaN

Dataset 5

,Particulars,Frequency,Unit,3-1993,3-1994,3-1995,3-1996,3-1997,3-1998,3-1999,3-2000,3-2001,3-2002,3-2003,3-2004,3-2005,3-2006,3-2007,3-2008,3-2009,3-2010,3-2011,3-2012,3-2013,3-2014
0,Agricultural Production Foodgrains,"Annual, Ending mar Of Each Year",Ton mn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,198.36282,208.6016,217.28212,230.77504,234.466177,218.107372,244.491809,259.286253,257.13,264.3806
1,Agricultural Production Foodgrains Kharif,"Annual, Ending mar Of Each Year",Ton mn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103.30942,109.8734,110.57622,120.95724,118.138577,103.954032,120.853191,131.274812,128.07,129.3686
2,Agricultural Production Foodgrains Rabi,"Annual, Ending mar Of Each Year",Ton mn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.05340,98.7282,106.70590,109.81780,116.327600,114.153340,123.638618,128.011441,129.06,135.0120
3,Agricultural Production Foodgrains Rice,"Annual, Ending mar Of Each Year",Ton mn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.13170,91.7934,93.35530,96.69290,99.182500,89.092901,95.979819,105.301100,105.24,106.2872
4,Agricultural Production Foodgrains Rice Kharif,"Annual, Ending mar Of Each Year",Ton mn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72.23000,78.2719,80.17080,82.65940,84.908200,75.916510,80.651241,92.780700,92.37,92.0093

In [6]:
# Display basic information about each dataset

for name, df in datasets.items():
    print(f"\n{'='*60}")
    print(name)
    print('='*60)
    df.info()

============================================================
Dataset 1
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Crop     12 non-null     str
 1   2004-05  12 non-null     float64
 2   2005-06  12 non-null     float64
 3   2006-07  12 non-null     float64
 4   2007-08  12 non-null     float64
 5   2008-09  12 non-null     float64
 6   2009-10  12 non-null     float64
 7   2010-11  12 non-null     float64
 8   2011-12  12 non-null     float64
dtypes: float64(8), str(1)
memory usage: 1.0 KB

============================================================
Dataset 2
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 6 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Crop                                   49 non-null     str
 1   State                                  49 non-null     str
 2   Cost of Cultivation (`/Hectare) A2+FL  49 non-null     float64
 3   Cost of Cultivation (`/Hectare) C2     49 non-null     float64
 4   Cost of Production (`/Quintal) C2      49 non-null     float64
 5   Yield (Quintal/ Hectare)               49 non-null     float64
dtypes: float64(4), str(2)
memory usage: 2.4 KB

============================================================
Dataset 3
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Crop                55 non-null     str
 1   Production 2006-07  55 non-null     float64
 2   Production 2007-08  55 non-null     float64
 3   Production 2008-09  55 non-null     float64
 4   Production 2009-10  55 non-null     float64
 5   Production 2010-11  55 non-null     float64
 6   Area 2006-07        55 non-null     float64
 7   Area 2007-08        55 non-null     float64
 8   Area 2008-09        55 non-null     float64
 9   Area 2009-10        55 non-null     float64
 10  Area 2010-11        55 non-null     float64
 11  Yield 2006-07       55 non-null     float64
 12  Yield 2007-08       55 non-null     float64
 13  Yield 2008-09       55 non-null     float64
 14  Yield 2009-10       55 non-null     float64
 15  Yield 2010-11       55 non-null     float64
dtypes: float64(15), str(1)
memory usage: 7.0 KB

============================================================
Dataset 4
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Crop                      78 non-null     str
 1   Variety                   78 non-null     str
 2   Season/ duration in days  50 non-null     str
 3   Recommended Zone          77 non-null     str
 4   Unnamed: 4                0 non-null      float64
dtypes: float64(1), str(4)
memory usage: 3.2 KB

============================================================
Dataset 5
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 429 entries, 0 to 428
Data columns (total 25 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Particulars  429 non-null    str
 1   Frequency    429 non-null    str
 2   Unit         429 non-null    str
 3    3-1993      3 non-null      float64
 4    3-1994      4 non-null      float64
 5    3-1995      4 non-null      float64
 6    3-1996      6 non-null      float64
 7    3-1997      10 non-null     float64
 8    3-1998      10 non-null     float64
 9    3-1999      11 non-null     float64
 10   3-2000      20 non-null     float64
 11   3-2001      22 non-null     float64
 12   3-2002      36 non-null     float64
 13   3-2003      128 non-null    float64
 14   3-2004      361 non-null    float64
 15   3-2005      425 non-null    float64
 16   3-2006      423 non-null    float64
 17   3-2007      418 non-null    float64
 18   3-2008      417 non-null    float64
 19   3-2009      418 non-null    float64
 20   3-2010      403 non-null    float64
 21   3-2011      404 non-null    float64
 22   3-2012      388 non-null    float64
 23   3-2013      298 non-null    float64
 24   3-2014      63 non-null     float64
dtypes: float64(22), str(3)
memory usage: 83.9 KB

In [7]:
# Check missing values

for name, df in datasets.items():
    print(f"\n{name}")
    print(df.isnull().sum())

Dataset 1
Crop       1
2004-05    1
2005-06    1
2006-07    1
2007-08    1
2008-09    1
2009-10    1
2010-11    1
2011-12    1
dtype: int64

Dataset 2
Crop                                     0
State                                    0
Cost of Cultivation (`/Hectare) A2+FL    0
Cost of Cultivation (`/Hectare) C2       0
Cost of Production (`/Quintal) C2        0
Yield (Quintal/ Hectare)                 0
dtype: int64

Dataset 3
Crop                  0
Production 2006-07    0
Production 2007-08    0
Production 2008-09    0
Production 2009-10    0
Production 2010-11    0
Area 2006-07          0
Area 2007-08          0
Area 2008-09          0
Area 2009-10          0
Area 2010-11          0
Yield 2006-07         0
Yield 2007-08         0
Yield 2008-09         0
Yield 2009-10         0
Yield 2010-11         0
dtype: int64

Dataset 4
Crop                         0
Variety                      0
Season/ duration in days    28
Recommended Zone             1
Unnamed: 4                  78
dtype: int64

Dataset 5
Particulars      0
Frequency        0
Unit             0
 3-1993        426
 3-1994        425
 3-1995        425
 3-1996        423
 3-1997        419
 3-1998        419
 3-1999        418
 3-2000        409
 3-2001        407
 3-2002        393
 3-2003        301
 3-2004         68
 3-2005          4
 3-2006          6
 3-2007         11
 3-2008         12
 3-2009         11
 3-2010         26
 3-2011         25
 3-2012         41
 3-2013        131
 3-2014        366
dtype: int64

In [8]:
# Check duplicate rows

for name, df in datasets.items():
    print(f"{name}: {df.duplicated().sum()} duplicate rows")

Dataset 1: 0 duplicate rows
Dataset 2: 0 duplicate rows
Dataset 3: 0 duplicate rows
Dataset 4: 0 duplicate rows
Dataset 5: 0 duplicate rows

In [9]:
# Statistical summary

for name, df in datasets.items():
    print(f"\n{name}")
    display(df.describe())

Dataset 1

,2004-05,2005-06,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12
count,12.0,12.00000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,100.0,99.75000,102.000000,104.750000,106.416667,114.916667,121.916667,120.750000
std,0.0,6.64865,12.634728,10.963783,11.261022,15.900019,11.405408,12.800036
min,100.0,86.00000,85.000000,87.000000,80.000000,81.000000,99.000000,102.000000
25%,100.0,96.75000,96.250000,97.750000,101.250000,106.250000,116.250000,109.500000
50%,100.0,100.00000,100.000000,102.000000,107.500000,115.500000,122.500000,120.500000
75%,100.0,103.25000,104.750000,115.000000,113.000000,123.250000,129.250000,130.750000
max,100.0,109.00000,134.000000,124.000000,124.000000,146.000000,138.000000,140.000000

Dataset 2

,Cost of Cultivation (`/Hectare) A2+FL,Cost of Cultivation (`/Hectare) C2,Cost of Production (`/Quintal) C2,Yield (Quintal/ Hectare)
count,49.000000,49.000000,49.000000,49.000000
mean,20363.537347,31364.666735,1620.537755,98.086735
std,13561.435306,20095.783569,1104.990472,245.293123
min,5483.540000,7868.640000,85.790000,1.320000
25%,12774.410000,19259.840000,732.620000,9.590000
50%,17022.000000,25909.050000,1595.560000,13.700000
75%,24731.060000,35423.480000,2228.970000,36.610000
max,66335.060000,91442.630000,5777.480000,1015.450000

Dataset 3

,Production 2006-07,Production 2007-08,Production 2008-09,Production 2009-10,Production 2010-11,Area 2006-07,Area 2007-08,Area 2008-09,Area 2009-10,Area 2010-11,Yield 2006-07,Yield 2007-08,Yield 2008-09,Yield 2009-10,Yield 2010-11
count,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000
mean,168.698182,182.629091,179.952727,173.749091,210.181818,116.025455,118.403636,120.530909,118.203636,127.216364,146.829091,153.774545,149.476364,147.427273,164.570909
std,179.503163,199.671545,187.409253,184.231322,232.535985,37.990960,41.287797,44.460177,44.976615,54.842653,144.836331,153.243102,141.412539,143.963743,160.925948
min,53.900000,54.400000,50.000000,42.900000,42.100000,47.900000,47.400000,43.600000,37.500000,36.100000,86.000000,75.300000,72.700000,80.700000,80.800000
25%,124.500000,122.200000,116.050000,105.350000,126.900000,92.550000,93.300000,93.200000,88.650000,90.650000,106.800000,116.800000,110.950000,108.300000,121.050000
50%,142.700000,160.100000,156.500000,140.300000,169.000000,120.700000,121.700000,121.900000,120.900000,129.400000,118.700000,124.500000,123.600000,122.100000,138.900000
75%,184.300000,200.100000,188.550000,197.050000,217.350000,131.050000,135.800000,136.250000,134.800000,147.950000,137.600000,154.400000,148.500000,142.800000,168.850000
max,1427.700000,1571.500000,1463.000000,1430.300000,1790.600000,222.700000,241.600000,254.500000,260.300000,314.700000,1176.600000,1247.700000,1156.800000,1172.100000,1310.800000

Dataset 4

       Unnamed: 4
count         0.0
mean          NaN
std           NaN
min           NaN
25%           NaN
50%           NaN
75%           NaN
max           NaN

Dataset 5

,3-1993,3-1994,3-1995,3-1996,3-1997,3-1998,3-1999,3-2000,3-2001,3-2002,3-2003,3-2004,3-2005,3-2006,3-2007,3-2008,3-2009,3-2010,3-2011,3-2012,3-2013,3-2014
count,3.0,4.0,4.0,6.000000,10.000000,10.000000,11.000000,20.000000,22.000000,36.000000,128.000000,361.000000,425.000000,423.000000,418.000000,417.000000,418.000000,403.000000,404.000000,388.000000,298.000000,63.000000
mean,0.0,0.0,0.0,6.753000,1310.623000,1276.252000,1146.230909,621.747000,588.115000,425.641667,1192.040313,1302.871184,1103.899915,1136.604858,1146.262067,1213.930482,1234.754599,1144.015426,1228.541458,1352.353707,1355.741134,252.303495
std,0.0,0.0,0.0,16.337482,4128.680346,4019.889103,3777.583647,2708.616162,2682.320751,2152.677440,6455.755638,4420.090474,3910.204724,3925.459550,3936.081939,4046.762259,4146.021269,4054.786966,4186.449378,4366.571068,2950.845362,670.745277
min,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.060000,0.060000,0.050000,0.058400,0.045000,0.050000,0.050000,0.087500
25%,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.390000,0.367500,2.400000,6.250000,5.920000,5.100000,5.589950,5.717500,5.748600,5.827500,5.378950,5.632750,5.780000,4.322500,2.853700
50%,0.0,0.0,0.0,0.000000,0.215000,0.230000,0.460000,4.050000,4.920000,15.850000,23.550000,73.300000,36.800000,36.520000,37.715000,40.760000,42.885000,43.770000,45.500000,43.830000,77.850000,13.451800
75%,0.0,0.0,0.0,0.313500,3.290000,2.875000,14.470000,30.775000,25.575000,81.475000,484.750000,1380.000000,1082.000000,1127.000000,1193.250000,1349.000000,1297.250000,1228.000000,1365.250000,1592.250000,1857.000000,93.929250
max,0.0,0.0,0.0,40.100000,13061.000000,12717.000000,12536.000000,12129.000000,12597.000000,12963.000000,69202.000000,69065.000000,65945.000000,64473.000000,64969.000000,66151.000000,67024.000000,67929.000000,68554.000000,69118.000000,30300.000000,3059.000000